# Generated by Django 6.0.6 on 2026-06-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="match",
            name="winner",
        ),
        migrations.AlterField(
            model_name="wallet",
            name="electis_balance",
            field=models.IntegerField(default=50),
        ),
        migrations.DeleteModel(
            name="ElectisTransaction",
        ),
    ]
