# Generated by Django 6.0.6 on 2026-07-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_email", models.EmailField(max_length=254)),
                ("child_name", models.CharField(max_length=200)),
                ("booked_date", models.DateField(unique=True)),
            ],
        ),
    ]
