# Generated by Django 6.0.6 on 2026-07-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="child_grade",
            field=models.CharField(default="No Detail Associated", max_length=10),
        ),
        migrations.AddField(
            model_name="reservation",
            name="parent_name",
            field=models.CharField(default="No Detail Associated", max_length=200),
        ),
        migrations.AddField(
            model_name="reservation",
            name="parent_phone",
            field=models.CharField(default="No Detail Associated", max_length=20),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="child_name",
            field=models.CharField(default="No Detail Associated", max_length=200),
        ),
    ]
