# Generated by Django 6.0.6 on 2026-07-18 21:37

import django.db.models.deletion
import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_reservation_child_grade_reservation_parent_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FormConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=forms.models.generate_form_code,
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(default="My Custom Form", max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Short Text"),
                            ("textarea", "Long Paragraph"),
                            ("number", "Number"),
                            ("email", "Email Address"),
                            ("checkbox", "Checkbox (True/False)"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="forms.formconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="forms.formconfiguration",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Reservation",
        ),
        migrations.AddField(
            model_name="fieldresponse",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="forms.formfield"
            ),
        ),
        migrations.AddField(
            model_name="fieldresponse",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="forms.formsubmission",
            ),
        ),
    ]
