# Generated by Django 6.0.6 on 2026-07-18 22:01

import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0004_formconfiguration_creator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formconfiguration",
            name="secret_token",
            field=models.CharField(
                default=forms.models.generate_secret_token, max_length=5, unique=True
            ),
        ),
    ]
