# Generated by Django 6.0.6 on 2026-10-07 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0005_formconfiguration_secret_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formfield",
            old_name="is_required",
            new_name="calender_is_required",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="field_type",
        ),
        migrations.AddField(
            model_name="formfield",
            name="calender_field_type",
            field=models.CharField(
                choices=[
                    ("text", "Short Text"),
                    ("textarea", "Long Paragraph"),
                    ("number", "Number"),
                    ("email", "Email Address"),
                    ("checkbox", "Checkbox (True/False)"),
                    ("calender", "Calendar Booking Slot"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CalenderAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_of_week", models.IntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("BLOCK", "Fixed Block (Single Session)"),
                            ("INTERVAL", "Interval Spans (Split into smaller slots)"),
                        ],
                        default="INTERVAL",
                        max_length=10,
                    ),
                ),
                ("interval_minutes", models.PositiveIntegerField(default=30)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_rules",
                        to="forms.formconfiguration",
                    ),
                ),
            ],
        ),
    ]
