# Generated by Django 6.0.6 on 2026-10-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0006_rename_is_required_formfield_calender_is_required_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calenderavailability",
            name="day_of_week",
        ),
        migrations.RemoveField(
            model_name="calenderavailability",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="calenderavailability",
            name="start_time",
        ),
        migrations.AddField(
            model_name="calenderavailability",
            name="end_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="calenderavailability",
            name="start_datetime",
            field=models.DateTimeField(null=True),
        ),
    ]
