from django.db import models
from django.contrib.auth.models import User
import uuid
import random
import string
from django.conf import settings
from cryptography.fernet import Fernet
from django.db import models
from django.conf import settings

class DMConversation(models.Model):
    user1 = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="dm_conversations_as_user1")
    user2 = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="dm_conversations_as_user2")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        # Ensures only one DM thread exists per pair of users
        unique_together = ('user1', 'user2')

    @classmethod
    def get_or_create_conversation(cls, u1, u2):
        """Helper to get or create a thread regardless of user ordering."""
        if u1.id > u2.id:
            u1, u2 = u2, u1
        return cls.objects.get_or_create(user1=u1, user2=u2)

class DirectMessage(models.Model):
    conversation = models.ForeignKey(DMConversation, on_delete=models.CASCADE, related_name="messages")
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    class Meta:
        ordering = ['timestamp']

class WebPushSubscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='push_subscriptions')
    endpoint = models.URLField(max_length=500)
    p256dh = models.CharField(max_length=150)
    auth = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Push Subscription for {self.user.username}"

# Function to generate a random 5-digit uppercase invite code
def generate_invite_code():
    while True:
        code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=5))
        # Ensure uniqueness
        if not PrivateChatRoom.objects.filter(invite_code=code).exists():
            return code

class PrivateChatRoom(models.Model):
    name = models.CharField(max_length=100)
    # Icon can be an emoji, text, or image URL. Keeping it simple as CharField for now.
    icon = models.CharField(max_length=255, default="💬")
    invite_code = models.CharField(max_length=5, unique=True, default=generate_invite_code)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owned_private_rooms')
    created_at = models.DateTimeField(auto_now_add=True)
    users = models.ManyToManyField(User, through='PrivateChatMembership', related_name='private_rooms')

    def __str__(self):
        return self.name

class PrivateChatMembership(models.Model):
    # This is the "long hex code" unique to the user for the URL
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(PrivateChatRoom, on_delete=models.CASCADE)
    joined_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'room') # User can't join same room twice


class PrivateMessage(models.Model):
    room = models.ForeignKey('PrivateChatRoom', on_delete=models.CASCADE, related_name='messages')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # This field will now securely store the encrypted string inside your database
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    # --- NEW TRACKING FIELDS ---
    is_edited = models.BooleanField(default=False)
    is_unsent = models.BooleanField(default=False)

    # Many-to-Many tracks exactly which users have fetched/rendered this message
    read_by = models.ManyToManyField(User, related_name='read_private_messages', blank=True)

    class Meta:
        ordering = ['timestamp']

    def save(self, *args, **kwargs):
        # Automatically encrypts the text string if it isn't already encrypted
        # 'gAAAAA' is the global standard token prefix generated by Fernet tokens
        if self.message and not self.message.startswith('gAAAAA'):
            f = Fernet(settings.FIELD_ENCRYPTION_KEY.encode())
            encrypted_bytes = f.encrypt(self.message.encode())
            self.message = encrypted_bytes.decode()
        super().save(*args, **kwargs)

    @property
    def get_decrypted_message(self):
        """Call this in your template as {{ message.get_decrypted_message }} to read the real text"""
        if self.is_unsent:
            return "This message was unsent."

        try:
            f = Fernet(settings.FIELD_ENCRYPTION_KEY.encode())
            decrypted_bytes = f.decrypt(self.message.encode())
            return decrypted_bytes.decode()
        except Exception:
            return "[Error: Asset decryption failed safely.]"
class ChatMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)