# Generated by Django 6.0.6 on 2026-09-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eliteos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="installedapp",
            name="unique_eliteos_installed_app",
        ),
        migrations.RemoveField(
            model_name="osnotification",
            name="user",
        ),
        migrations.RemoveField(
            model_name="osproject",
            name="user",
        ),
        migrations.RemoveField(
            model_name="osprofile",
            name="accent",
        ),
        migrations.RemoveField(
            model_name="osprofile",
            name="animations",
        ),
        migrations.RemoveField(
            model_name="osprofile",
            name="taskbar_position",
        ),
        migrations.RemoveField(
            model_name="osprofile",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="osprofile",
            name="wallpaper",
        ),
        migrations.AddField(
            model_name="osprofile",
            name="boot_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="osprofile",
            name="compressed_size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="osprofile",
            name="filesystem_image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="osprofile",
            name="filesystem_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="osprofile",
            name="last_booted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="installedapp",
            name="user",
        ),
        migrations.DeleteModel(
            name="OSFile",
        ),
        migrations.DeleteModel(
            name="OSNotification",
        ),
        migrations.DeleteModel(
            name="OSProject",
        ),
        migrations.DeleteModel(
            name="InstalledApp",
        ),
    ]
