# Generated by Django 6.0.6 on 2026-09-07 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eliteos", "0002_remove_installedapp_unique_eliteos_installed_app_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="osprofile",
            name="compressed_size",
        ),
        migrations.RemoveField(
            model_name="osprofile",
            name="filesystem_image",
        ),
        migrations.RemoveField(
            model_name="osprofile",
            name="filesystem_version",
        ),
        migrations.AddField(
            model_name="osprofile",
            name="accent",
            field=models.CharField(default="#6366f1", max_length=30),
        ),
        migrations.AddField(
            model_name="osprofile",
            name="animations",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="osprofile",
            name="taskbar_position",
            field=models.CharField(default="bottom", max_length=20),
        ),
        migrations.AddField(
            model_name="osprofile",
            name="theme",
            field=models.CharField(default="dark", max_length=20),
        ),
        migrations.AddField(
            model_name="osprofile",
            name="wallpaper",
            field=models.CharField(
                default="linear-gradient(135deg, #080b18, #101a38, #172554)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="osprofile",
            name="boot_count",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="OSFilesystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.BinaryField(default=bytes)),
                ("compressed_size", models.PositiveIntegerField(default=0)),
                ("filesystem_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eliteos_filesystem",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OSNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("notification_type", models.CharField(default="info", max_length=30)),
                ("read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eliteos_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OSProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eliteos_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstalledApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.CharField(max_length=100)),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eliteos_installed_apps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "app_id"), name="unique_eliteos_installed_app"
                    )
                ],
            },
        ),
    ]
