# Generated by Django 6.0.6 on 2026-09-07 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eliteos", "0003_remove_osprofile_compressed_size_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="osprofile",
            name="compact_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="osprofile",
            name="show_desktop_icons",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="osprofile",
            name="wallpaper",
            field=models.CharField(default="aurora", max_length=1000),
        ),
        migrations.CreateModel(
            name="AppSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.SlugField(max_length=100)),
                ("name", models.CharField(max_length=120)),
                ("version", models.CharField(default="1.0", max_length=30)),
                ("description", models.TextField(max_length=1000)),
                ("icon", models.CharField(default="📦", max_length=20)),
                ("manifest", models.JSONField(default=dict)),
                ("application", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eliteos_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
