# Generated by Django 6.0.6 on 2026-09-07 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eliteos",
            "0004_osprofile_compact_mode_osprofile_show_desktop_icons_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="osprofile",
            name="show_desktop_icons",
        ),
        migrations.AddField(
            model_name="osprofile",
            name="icon_size",
            field=models.PositiveIntegerField(default=44),
        ),
        migrations.AlterField(
            model_name="osprofile",
            name="accent",
            field=models.CharField(default="#2563eb", max_length=30),
        ),
        migrations.AlterField(
            model_name="osprofile",
            name="wallpaper",
            field=models.CharField(
                default="linear-gradient(135deg,#1e293b 0%,#334155 45%,#0f172a 100%)",
                max_length=1000,
            ),
        ),
        migrations.CreateModel(
            name="StoreApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="1.0.0", max_length=30)),
                ("icon", models.CharField(default="▦", max_length=20)),
                ("package", models.JSONField(default=dict)),
                ("published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eliteos_store_apps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AppSubmission",
        ),
    ]
