# Generated by Django 6.0.6 on 2026-09-07 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eliteos", "0005_remove_osprofile_show_desktop_icons_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="osprofile",
            name="compact_mode",
        ),
        migrations.RemoveField(
            model_name="osprofile",
            name="icon_size",
        ),
        migrations.AddField(
            model_name="osprofile",
            name="blur",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="osprofile",
            name="transparency",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="osfilesystem",
            name="filesystem_version",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="osprofile",
            name="accent",
            field=models.CharField(default="#4f9d69", max_length=30),
        ),
        migrations.AlterField(
            model_name="osprofile",
            name="taskbar_position",
            field=models.CharField(
                choices=[("bottom", "Bottom"), ("top", "Top")],
                default="bottom",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="osprofile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("mint", "Mint"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("midnight", "Midnight"),
                    ("high-contrast", "High Contrast"),
                ],
                default="mint",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="osprofile",
            name="wallpaper",
            field=models.CharField(default="mint", max_length=1000),
        ),
        migrations.AlterField(
            model_name="storeapp",
            name="icon",
            field=models.CharField(default="🧩", max_length=20),
        ),
        migrations.AlterField(
            model_name="storeapp",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eliteos_published_apps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
