# Generated by Django 6.0.6 on 2026-09-09 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eliteos", "0006_remove_osprofile_compact_mode_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="osproject",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="storeapp",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="installedapp",
            name="unique_eliteos_installed_app",
        ),
        migrations.RenameField(
            model_name="storeapp",
            old_name="package",
            new_name="source",
        ),
        migrations.RemoveField(
            model_name="osprofile",
            name="blur",
        ),
        migrations.RemoveField(
            model_name="osprofile",
            name="taskbar_position",
        ),
        migrations.RemoveField(
            model_name="storeapp",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="storeapp",
            name="published",
        ),
        migrations.AddField(
            model_name="osprofile",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="osprofile",
            name="panel_position",
            field=models.CharField(default="bottom", max_length=20),
        ),
        migrations.AddField(
            model_name="storeapp",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eliteos_store_apps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="storeapp",
            name="downloads",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="storeapp",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="osfilesystem",
            name="filesystem_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="osprofile",
            name="accent",
            field=models.CharField(default="#5b8cff", max_length=30),
        ),
        migrations.AlterField(
            model_name="osprofile",
            name="theme",
            field=models.CharField(default="dark", max_length=20),
        ),
        migrations.AlterField(
            model_name="osprofile",
            name="transparency",
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AlterField(
            model_name="osprofile",
            name="wallpaper",
            field=models.CharField(
                default="radial-gradient(circle at 20% 20%, #4267ff 0%, transparent 35%), radial-gradient(circle at 80% 80%, #8b5cf6 0%, transparent 40%), linear-gradient(135deg, #07111f, #0c1930, #10264a)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="storeapp",
            name="app_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="storeapp",
            name="icon",
            field=models.CharField(default="◈", max_length=20),
        ),
        migrations.AlterField(
            model_name="storeapp",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="installedapp",
            constraint=models.UniqueConstraint(
                fields=("user", "app_id"), name="eliteos_unique_installed_app"
            ),
        ),
        migrations.DeleteModel(
            name="OSProject",
        ),
    ]
