# Generated by Django 6.0.6 on 2026-09-19 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eliteos", "0007_remove_osproject_user_alter_storeapp_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="osprofile",
            name="accent",
            field=models.CharField(default="#4f7cff", max_length=30),
        ),
        migrations.AlterField(
            model_name="osprofile",
            name="transparency",
            field=models.PositiveIntegerField(default=78),
        ),
        migrations.AlterField(
            model_name="osprofile",
            name="wallpaper",
            field=models.CharField(
                default="radial-gradient(circle at 20% 20%, #4f7cff 0%, transparent 30%), radial-gradient(circle at 80% 25%, #7c3aed 0%, transparent 32%), radial-gradient(circle at 50% 100%, #0ea5e9 0%, transparent 40%), linear-gradient(135deg, #06111f, #0d1d33)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="storeapp",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eliteos_store_apps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
