# Generated by Django 5.1.3 on 2026-06-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elitedevelop", "0002_developerprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developerprofile",
            name="face_descriptor",
            field=models.TextField(blank=True, null=True),
        ),
    ]
