# Generated by Django 5.1.3 on 2026-06-15 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elitedevelop", "0003_alter_developerprofile_face_descriptor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeveloperProfile",
        ),
    ]
