# Generated by Django 6.0.6 on 2026-06-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elitedevelop", "0005_codesnippet"),
    ]

    operations = [
        migrations.CreateModel(
            name="inDevelopment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indev", models.BooleanField(default=False)),
            ],
        ),
    ]
