# Generated by Django 6.0.6 on 2026-06-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elitedevelop", "0006_indevelopment"),
    ]

    operations = [
        migrations.AddField(
            model_name="indevelopment",
            name="reason",
            field=models.CharField(default="?", max_length=1000),
        ),
    ]
