# Generated by Django 6.0.6 on 2026-07-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elitedevelop", "0008_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="about_me",
            field=models.CharField(default="No bio yet...", max_length=1000),
        ),
    ]
