# Generated by Django 6.0.6 on 2026-07-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elitedevelop", "0009_userprofile_about_me"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="about_me",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
