# Generated by Django 6.0.6 on 2026-07-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elitedevelop", "0010_alter_userprofile_about_me"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="consent_form",
            field=models.ImageField(blank=True, null=True, upload_to="consent_forms/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_child",
            field=models.BooleanField(default=False),
        ),
    ]
