# Generated by Django 6.0.6 on 2026-07-19 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "elitedevelop",
            "0011_userprofile_consent_form_userprofile_is_approved_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="consent_form",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="has_math_access",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_child",
        ),
    ]
