# Generated by Django 6.0.6 on 2026-07-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elitedevelop", "0012_remove_userprofile_consent_form_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_active_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
