# Generated by Django 6.0.6 on 2026-07-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elitedevelop", "0013_userprofile_current_streak_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="seconds_today",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="streak_earned_today",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="about_me",
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
