# Generated by Django 6.0.6 on 2026-07-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elitedevelop", "0014_userprofile_seconds_today_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="seconds_today",
            field=models.IntegerField(default=0),
        ),
    ]
