# Generated by Django 6.0.6 on 2026-07-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elitedevelop", "0015_alter_userprofile_seconds_today"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ai_access",
            field=models.BooleanField(default=False),
        ),
    ]
