# Generated by Django 6.0.6 on 2026-09-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elitedevelop", "0018_requestlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="proxy_requests_per_day",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="proxy_requests_reset_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="proxy_requests_today",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
