# Generated by Django 6.0.6 on 2026-09-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elitedevelop", "0019_userprofile_proxy_requests_per_day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="ai_access",
        ),
    ]
