# Generated by Django 6.0.6 on 2026-09-27 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elitedevelop", "0021_organization_organizationmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_organization_account",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="organization",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="account",
                to="elitedevelop.organization",
            ),
        ),
    ]
