# Generated by Django 5.1.3 on 2026-05-21 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_privatechatmembership_privatechatroom_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemessage",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="is_unsent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="read_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="read_private_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
