# Generated by Django 5.1.3 on 2026-06-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_privatemessagereaction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PrivateMessageReaction",
        ),
    ]
