from django.db import models
from django.contrib.auth.models import User
import uuid
from django.conf import settings
from cryptography.fernet import Fernet
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils import timezone
import datetime
from django.db import models
from django.conf import settings

class RequestLog(models.Model):
    path = models.CharField(max_length=255)
    method = models.CharField(max_length=10)
    status_code = models.IntegerField()
    duration_ms = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)
class UserBlock(models.Model):
    blocker = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='blocking', on_delete=models.CASCADE)
    blocked = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='blocked_by', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('blocker', 'blocked')

    def __str__(self):
        return f"{self.blocker.username} blocked {self.blocked.username}"


class UserReport(models.Model):
    REASON_CHOICES = [
        ('spam', 'Spam or Advertising'),
        ('harassment', 'Harassment or Bullying'),
        ('inappropriate', 'Inappropriate Content'),
        ('other', 'Other'),
    ]

    reporter = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='reports_sent', on_delete=models.CASCADE)
    reported_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='reports_received', on_delete=models.CASCADE)
    reason = models.CharField(max_length=20, choices=REASON_CHOICES)
    details = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Report by {self.reporter.username} against {self.reported_user.username}"
@receiver(pre_save, sender=User)
def auto_link_existing_user_by_email(sender, instance, **kwargs):
    """
    If a new user is being created via OAuth2 with a matching email,
    prevent a new random username from being generated by pointing to
    the existing account instead.
    """
    # Only run this check if the user is new (has no primary key yet) and has an email
    if not instance.pk and instance.email:
        try:
            existing_user = User.objects.get(email__iexact=instance.email)
            # Match found! Copy over the existing user ID so Django updates
            # the existing account instead of inserting a duplicate row.
            instance.pk = existing_user.pk
            instance.username = existing_user.username
        except User.DoesNotExist:
            # No existing user found with this email; proceed with normal creation.
            pass

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    current_streak = models.PositiveIntegerField(default=0)
    seconds_today = models.IntegerField(default=0)
    streak_earned_today = models.BooleanField(default=False)
    last_active_date = models.DateField(null=True, blank=True)
    about_me = models.CharField(max_length=10000, blank=True)
    proxy_requests_per_day = models.PositiveIntegerField(default=10)
    proxy_requests_today = models.PositiveIntegerField(default=0)
    proxy_requests_reset_date = models.DateField(null=True, blank=True)

    def add_active_time(self, seconds=5):
        today = timezone.now().date()

        # 1. Reset counters on a new calendar day
        if self.last_active_date != today:
            # Check if user missed yesterday (broken streak) before updating last_active_date
            if self.last_active_date and self.last_active_date < today - datetime.timedelta(days=1):
                self.current_streak = 0

            self.seconds_today = 0
            self.streak_earned_today = False
            self.last_active_date = today

        just_unlocked = False

        # 2. Increment active time until 15 minutes (900s) is reached
        if not self.streak_earned_today:
            self.seconds_today += seconds

            if self.seconds_today >= 900:
                self.streak_earned_today = True
                self.current_streak += 1
                just_unlocked = True

        self.save()
        return just_unlocked

    def __str__(self):
        return f"{self.user.username}'s Profile"
# Replace BOTH old signal functions in models.py with this single one:
@receiver(post_save, sender=User)
def manage_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.get_or_create(user=instance)
    else:
        # Use safe guard to only save if the profile exists
        if hasattr(instance, 'profile'):
            instance.profile.save()

class inDevelopment(models.Model):
    indev = models.BooleanField(default=False)
    reason = models.CharField(max_length=1000, default="?")
    @property
    def status(self):
        return {
            'indev': self.indev,
            'reason': self.reason if self.indev else ""
        }
class CodeSnippet(models.Model):
    # Generates a random secure share link string (e.g., /vault/share/abc-123/)
    share_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='snippets')
    title = models.CharField(max_length=150, default="Untitled Snippet")
    language = models.CharField(max_length=50, default="python")

    # Encrypted code block
    encrypted_code = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-timestamp']

    def save(self, *args, **kwargs):
        if self.encrypted_code and not self.encrypted_code.startswith('gAAAAA'):
            f = Fernet(settings.FIELD_ENCRYPTION_KEY.encode())
            encrypted_bytes = f.encrypt(self.encrypted_code.encode())
            self.encrypted_code = encrypted_bytes.decode()
        super().save(*args, **kwargs)

    @property
    def get_decrypted_code(self):
        try:
            f = Fernet(settings.FIELD_ENCRYPTION_KEY.encode())
            decrypted_bytes = f.decrypt(self.encrypted_code.encode())
            return decrypted_bytes.decode()
        except Exception:
            return "// Error: Code asset decryption failed."
class UserActivityLog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='activity_logs')
    action_type = models.CharField(max_length=50)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-timestamp']